In [ ]:
## In this module we will learn to code in Numpy Library used in Python

In [13]:
import numpy as np

arr = np.array([[1, 2, 4]
               ,[6, 7, 8],
                [8, 9, 0]])

print(arr.dtype)


int64


In [16]:
u1 = np.array([2, 4, 5])
u2 = np.array([[2],
              [5]])

print(u1 + u2)

[[ 4  6  7]
 [ 7  9 10]]


In [25]:
fill = np.full([3, 1, 2], 7)

print(fill)

[[[7 7]]

 [[7 7]]

 [[7 7]]]


In [31]:
randoms = np.random.randint(1, 25, (3, 3))
print(randoms)

[[ 4  1 13]
 [ 2 14 12]
 [11  2 21]]
